---
title: "README: epi_tutorial_library"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project description  
This repo contains a series of tutorials for quantitative epidemiologic methods in R. The primary focus will be on characterizing and modeling infectious disease.

## Table of Contents  
*The repo is organized into folders by methodology.*   

Summer2023Schedule  

+ .Rmd file is source code and .html is rendered output.  

+ Tentative schedule for topics to discuss. will be updated throughout the summer and populated with hyperlinks. [Here](https://rpubs.com/KNightingale/SUIP2023) is the published web page. 


**Spatial/**  
*A folder of sample codes to explore spatial data - both visualization and analysis.*   

01_Mapping  

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for making visually appealing maps using 3 methods: layering shapefiles, adding background tiles, creating interactive maps  

+ This [tutorial](https://rpubs.com/KNightingale/SUIP2023_01) runs through an example using freely accessible data on hospital locations in the city of Philadelphia.


02_ChoroplethMaps 

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for a tutorial on spatial visualization and analysis primarily focused on choropleth maps.  

+ Includes code to work with point,line, and polygon spatial data using the sf package.  

+ This [tutorial](https://rpubs.com/KNightingale/SUIP2023_2) runs through an example using freely accessible data on the city of Philadelphia looking at litter index and trashcan availability.  


03_Mapping Exercise

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ This is a practice exercise using publically available data from the city of Philadelphia.


04_GPStracking  

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for estimating home range from GPS tracking data using KDE and t-locoh.  

+ This [tutorial](https://rpubs.com/KNightingale/1060153) runs through an example using the t-locoh and kde examples.


05_SpatialClustering  

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for estimating spatial epi statistics including scan statistics for clustering, relative risk, and Moran's I.  

+ This [tutorial](https://rpubs.com/KNightingale/1060152) runs codes provided in package examples to execute these methods.

**TransmissionModels/**  
*A folder of sample codes for mathematical models of infectious disease transmission.*

06_Modelling Basics

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for a simple, deterministic, SIR model, plus addition of compartments. Also includes a practice exercise.

+ The [tutorial](https://rpubs.com/KNightingale/1062478) can be found here.   


05_MetapopulationModel 

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for a simple, deterministic, metapopulation model.

+ This [tutorial](https://rpubs.com/KNightingale/1062482) runs through 2 examples look at systems with 3 patches coupled in different configurations.   

06_StochasticSIR  

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for a simple, stochastic SIR model.  

+ This [tutorial](https://rpubs.com/KNightingale/1064573) runs through stochastic simulation code for a simple SIR model. 


07_MetapopulationModel 

+ The .Rmd file is the R markdown code and the .html file is the rendered html output.  

+ R code for metropolis hasting sampler to estimate parameters for simulated SIR data.

+ This [tutorial](https://rpubs.com/KNightingale/1064580) corresponds to the code. 
