---
title: "GGEB SUIP Brief Epidemiology Tutorials"
author: Kira Nightingale
output:
  html_document:
    code_folding: show
    highlight: haddock
    number_sections: no
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The purpose of these brief epidemiology tutorials is to provide students with an introduction to spatial epidemiology and infectious disease transmission models. All tutorials will be conducted using R and publicly available data. The link for the github repository containing all 2023 tutorials can be found here: [link](https://github.com/kira-nightingale/epi_tutorial_library/tree/main). The original tutorial materials were created by Brinkley Raynor, PhD in 2022, and revised by Kira Nightingale in 2023.

# Session 1
**Friday, June 30**

### Mapping in R
This tutorial covers the basics of creating maps in R via three methods: layering shape files, adding a background of imported tiles, and using leaflet to create interactive maps. Uses publicly available data on hospital locations in Philadelphia.

- [Tutorial link](https://rpubs.com/KNightingale/SUIP2023_01)
- [Code link](https://github.com/kira-nightingale/epi_tutorial_library/blob/main/Spatial/01_Mapping.Rmd)

## Introduction to Spatial Epidemiology
Building on the mapping techniques in the prior tutorial, this session covers the creation of more complex maps and basic summary statistics. Uses publicly available data on litter index and trashcan locations in Philadelphia.

- [Tutorial link](https://rpubs.com/KNightingale/SUIP2023_2)
- [Code link](https://github.com/kira-nightingale/epi_tutorial_library/blob/main/Spatial/02_ChoroplethMaps.Rmd)

## Practice Exercise

- [Code link](https://github.com/kira-nightingale/epi_tutorial_library/blob/main/Spatial/03_MappingExercise.Rmd)
- [Sample Solution]("https://rpubs.com/KNightingale/1060151")

# Session 2
**Friday, July 7**

## GPS Data Analysis
Using data from a GPS collar fitted to a buffalo (Toni) in Kruger National Park, South Africa from 2005-2006, this tutorial introduces methods to analyze location data. Methods include basic plotting, kernel density estimation, and time local convex hull (t-LoCoH).

- [Tutorial link](https://rpubs.com/KNightingale/1060153)
- [Code link](https://github.com/kira-nightingale/epi_tutorial_library/blob/main/Spatial/04_GPStracking.Rmd)

## Classic Spatial Epidemiology
This module covers methods that can be used to identify clusters, such as scan statistics, spatial relative risk, and Moran's I.

- [Tutorial link](https://rpubs.com/KNightingale/1060152)
- [Code link](https://github.com/kira-nightingale/epi_tutorial_library/blob/main/Spatial/05_SpatialClustering.Rmd)

# Session 3
**Friday, July 14**

## Compartmental Models
- [Tutorial link](https://rpubs.com/KNightingale/1062478)
- [Code link]
- Solution link - will be added later

## Metapopulation Models
- [Tutorial link](https://rpubs.com/KNightingale/1062482)
- [Code link]()

# Session 4
**Friday, July 21**

## Stochastic Models
- Tutorial link
- Code link

## Inference for Transmission Models
- Tutorial link
- Code link